# Generated by Django 4.2.5 on 2026-06-24 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=30, unique=True, verbose_name='رقم الفاتورة')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('payment_type', models.CharField(choices=[('cash', 'نقدي'), ('credit', 'آجل')], default='cash', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحّلة')], default='draft', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الخصم')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الإجمالي')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المدفوع')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فاتورة مبيعات',
                'verbose_name_plural': 'فواتير المبيعات',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر البيع')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='خصم')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'بند مبيعات',
                'verbose_name_plural': 'بنود المبيعات',
            },
        ),
    ]
