# Generated by Django 4.2.5 on 2026-06-25 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0005_entity_codes'),
        ('pharmacy', '0002_barcodelabelsettings_branch'),
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='pharmacy.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='currency',
            field=models.CharField(default='ج.م', max_length=10, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='walk_in_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='اسم العميل النقدي'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='walk_in_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='موبايل العميل النقدي'),
        ),
        migrations.CreateModel(
            name='SalesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('cash', 'نقدي'), ('bank', 'بنك')], default='cash', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('notes', models.CharField(blank=True, max_length=120, verbose_name='ملاحظات')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.bank', verbose_name='البنك')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.salesinvoice')),
            ],
            options={
                'verbose_name': 'تحصيل فاتورة مبيعات',
                'verbose_name_plural': 'تحصيلات فواتير المبيعات',
            },
        ),
    ]
