# Generated by Django 4.2.5 on 2026-06-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sales_pos_customer_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesline',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تكلفة الوحدة'),
        ),
    ]
