# Generated by Django 4.2.5 on 2026-06-25 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treasury', '0005_entity_codes'),
        ('parties', '0003_sales_pos_customer_payment'),
        ('pharmacy', '0003_receipt_settings'),
        ('inventory', '0003_warehouse_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(max_length=30, unique=True, verbose_name='رقم المرتجع')),
                ('kind', models.CharField(choices=[('sales', 'مرتجع مبيعات'), ('purchase', 'مرتجع مشتريات')], max_length=10)),
                ('walk_in_name', models.CharField(blank=True, max_length=150)),
                ('walk_in_phone', models.CharField(blank=True, max_length=30)),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('posted', 'مرحّل')], default='draft', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_documents', to='pharmacy.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parties.customer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parties.supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'مرتجع فاتورة',
                'verbose_name_plural': 'مرتجعات الفواتير',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('cash', 'نقدي'), ('bank', 'بنك')], default='cash', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=120)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.bank')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='returns.returndocument')),
            ],
            options={
                'verbose_name': 'سداد مرتجع',
                'verbose_name_plural': 'سدادات المرتجعات',
            },
        ),
        migrations.CreateModel(
            name='ReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='returns.returndocument')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='الصنف')),
            ],
            options={
                'verbose_name': 'بند مرتجع',
                'verbose_name_plural': 'بنود المرتجعات',
            },
        ),
    ]
