# Generated by Django 4.2.5 on 2026-06-25 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_barcodelabelsettings_branch'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='pharmacy.branch', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير'), ('pharmacist', 'صيدلي'), ('cashier', 'كاشير'), ('accountant', 'محاسب')], default='cashier', max_length=20),
        ),
        migrations.CreateModel(
            name='UserModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', 'لوحة التحكم'), ('warehouses', 'المخازن'), ('categories', 'الأصناف الرئيسية'), ('companies', 'الشركات المنتجة'), ('products', 'الأصناف الفرعية'), ('stock', 'المخزون والأرصدة'), ('suppliers', 'الموردين'), ('customers', 'العملاء'), ('purchases', 'المشتريات'), ('sales', 'المبيعات'), ('expenses', 'المصروفات'), ('settings', 'الإعدادات')], max_length=20)),
                ('can_view', models.BooleanField(default=True, verbose_name='عرض')),
                ('can_add', models.BooleanField(default=False, verbose_name='إضافة')),
                ('can_edit', models.BooleanField(default=False, verbose_name='تعديل')),
                ('can_delete', models.BooleanField(default=False, verbose_name='حذف')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'صلاحية مستخدم',
                'verbose_name_plural': 'صلاحيات المستخدمين',
                'unique_together': {('user', 'module')},
            },
        ),
    ]
