# Generated by Django 4.2.5 on 2026-06-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrugCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المجموعة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'صنف رئيسي',
                'verbose_name_plural': 'الأصناف الرئيسية',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DrugCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الشركة')),
                ('country', models.CharField(blank=True, max_length=80, verbose_name='الدولة')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'شركة منتجة',
                'verbose_name_plural': 'الشركات المنتجة',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30, unique=True, verbose_name='كود الصنف')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الدواء')),
                ('unit', models.CharField(choices=[('box', 'علبة'), ('strip', 'شريط'), ('piece', 'قطعة'), ('bottle', 'زجاجة'), ('tube', 'أنبوبة')], default='box', max_length=10, verbose_name='الوحدة')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='الباركود')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تكلفة الشراء')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر البيع')),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='حد الطلب')),
                ('max_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الحد الأقصى')),
                ('expiry_alert_days', models.PositiveIntegerField(default=90, verbose_name='تنبيه قبل الانتهاء (يوم)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'صنف فرعي',
                'verbose_name_plural': 'الأصناف الفرعية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الكمية')),
                ('batch_number', models.CharField(blank=True, max_length=50, verbose_name='رقم التشغيلة')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الصلاحية')),
            ],
            options={
                'verbose_name': 'رصيد مخزن',
                'verbose_name_plural': 'أرصدة المخازن',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_type', models.CharField(choices=[('opening', 'رصيد افتتاحي'), ('purchase', 'مشتريات'), ('sale', 'مبيعات'), ('transfer', 'تحويل'), ('adjust_in', 'تسوية إضافة'), ('adjust_out', 'تسوية خصم'), ('return_in', 'مرتجع شراء'), ('return_out', 'مرتجع بيع')], max_length=15, verbose_name='نوع الحركة')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الكمية')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تكلفة الوحدة')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='مرجع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'حركة مخزنية',
                'verbose_name_plural': 'الحركات المخزنية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=120, verbose_name='اسم المخزن')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='الموقع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مخزن',
                'verbose_name_plural': 'المخازن',
                'ordering': ['code'],
            },
        ),
    ]
