# Generated by Django 4.2.5 on 2026-06-25 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_barcodelabelsettings_branch'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='pharmacy.branch', verbose_name='الفرع'),
        ),
    ]
