# Generated by Django 4.2.5 on 2026-06-25 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_barcodelabelsettings_branch'),
        ('treasury', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='treasury.expensecategory', verbose_name='البند'),
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود البنك')),
                ('name', models.CharField(max_length=120, verbose_name='اسم البنك / الحساب')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الحساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banks', to='pharmacy.branch', verbose_name='الفرع')),
            ],
            options={
                'verbose_name': 'بنك',
                'verbose_name_plural': 'البنوك',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='treasury.bank', verbose_name='البنك'),
        ),
    ]
