# Generated by Django 4.2.5 on 2026-06-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0003_alter_expense_category_bank_expense_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='الخزنة الرئيسية', max_length=80, verbose_name='الاسم')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الرصيد')),
            ],
            options={
                'verbose_name': 'خزنة نقدية',
                'verbose_name_plural': 'الخزائن النقدية',
            },
        ),
        migrations.AddField(
            model_name='bank',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الرصيد'),
        ),
    ]
