# Generated by Django 4.2.5 on 2026-06-25 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0004_cashbox_bank_balance'),
        ('purchases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseline',
            name='line_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ضريبة'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر البيع'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='خصم إجمالي'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='ضريبة إجمالية'),
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('cash', 'نقدي'), ('bank', 'بنك')], default='cash', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('notes', models.CharField(blank=True, max_length=120, verbose_name='ملاحظات')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.bank', verbose_name='البنك')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='purchases.purchaseinvoice')),
            ],
            options={
                'verbose_name': 'سداد مشتريات',
                'verbose_name_plural': 'سدادات المشتريات',
            },
        ),
    ]
