# Generated by Django 4.2.5 on 2026-06-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchaseline_line_tax_purchaseline_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='currency',
            field=models.CharField(default='ج.م', max_length=10, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='document_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='رقم المستند'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم التشغيلة'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='نسبة الخصم %'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الصلاحية'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='تكلفة شحن/قطعة'),
        ),
    ]
