# Generated by Django 4.2.5 on 2026-06-25 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_barcodelabelsettings_branch'),
        ('purchases', '0004_purchaseinvoice_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='pharmacy.branch', verbose_name='الفرع'),
        ),
    ]
